config/routes.rb
TestApp::Application.routes.draw do
  resources :secret_codes
  match 'generate_code' => 'secret_codes#generate_code'

  devise_for :users

  root :to => 'secret_codes#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
        can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
  # import "activerecord-import"
  attr_accessible :code, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name,:secret_code,:role
  validates :secret_code, :presence => true
  # ,:inclusion => { :in => "foobar" }
  # # attr_accessible :title, :body
  has_one :secretcode, :class_name => 'SecretCode', :foreign_key => "user_id"
  after_create :update_user
  # accepts_nested_attributes_for :secret_code,
  #                           :reject_if => :all_blank,
  #                           :allow_destroy => true

 def update_user
    code = SecretCode.find(secret_code)
    code.user_id = id
    code.save
 end
 def admin?
   return true if self.role == 'admin'
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from CanCan::AccessDenied do |exception|
     redirect_to root_url, :alert => exception.message
   end
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
    load_and_authorize_resource
  # GET /secret_codes
  # GET /secret_codes.json
  def index
    @secret_codes = SecretCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @secret_codes }
    end
  end

  # GET /secret_codes/1
  # GET /secret_codes/1.json
  def show
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/new
  # GET /secret_codes/new.json
  def new
    @secret_code = SecretCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/1/edit
  def edit
    @secret_code = SecretCode.find(params[:id])
  end

  # POST /secret_codes
  # POST /secret_codes.json
  def create
    @secret_code = SecretCode.new(params[:secret_code])

    respond_to do |format|
      if @secret_code.save
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully created.' }
        format.json { render json: @secret_code, status: :created, location: @secret_code }
      else
        format.html { render action: "new" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /secret_codes/1
  # PUT /secret_codes/1.json
  def update
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      if @secret_code.update_attributes(params[:secret_code])
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secret_codes/1
  # DELETE /secret_codes/1.json
  def destroy
    @secret_code = SecretCode.find(params[:id])
    @secret_code.destroy

    respond_to do |format|
      format.html { redirect_to secret_codes_url }
      format.json { head :no_content }
    end
  end

  def generate_code
    @codes = []
   code_times = params[:times].to_i
   if code_times == 1
     @codes << SecretCode.create(:code => SecureRandom.hex(3))
   else
   code_times.to_i.times do |i| 
      @codes << SecretCode.create(:code => SecureRandom.hex(3))
   end
 end
   # SecretCode.import codes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/dashboard/index.html.erb
<br />
<div class="container">
<div class="well well small">
<p>	Welcome To Test APP </p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name,msg| %>
<%= content_tag :div,msg, :id => "flash_#{name}" %>
<% end %>

 <div id="container">
 	<div id="user_nav">
 		<% if user_signed_in? %>
 		Signed in as <%=current_user.email %>.Not you?
 		<%= link_to "Sign Out", destroy_user_session_path %>
 		<% else %>
 		<%= link_to "sign_up", new_user_registration_path %> or <%= link_to "sign_in", new_user_session_path  %>
 		<% end %>
 		</div>
<%= yield %>

</div>

</body>
</html>

app/views/secret_codes/_form.html.erb
<%= form_for(@secret_code) do |f| %>
  <% if @secret_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secret_code.errors.count, "error") %> prohibited this secret_code from being saved:</h2>

      <ul>
      <% @secret_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secret_codes/edit.html.erb
<h1>Editing secret_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @secret_code %> |
<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/generate_code.html.erb
<h3><%= link_to 'Back', secret_codes_path %></h3>
<table class="table table-striped">
	<th>Name</th>
	<% @codes.each do |code| %>
	<tr>
      <td><%=code.code %></td>
    </tr>
    <% end %>

</table>

app/views/secret_codes/index.html.erb
<h1>Listing secret_codes</h1>

<table class="table table-striped">
  <tr>
    <th>User</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @secret_codes.each do |secret_code| %>
  <tr>
    <td><%= secret_code.user.try(:email) %></td>
    <td><%= secret_code.code %></td>

    <td><%= link_to 'Show', secret_code %></td>
    <% if can? :update, SecretCode %>
    <td><%= link_to 'Edit', edit_secret_code_path(secret_code) %></td>
    <td><%= link_to 'Destroy', secret_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :update, SecretCode %>
<%=form_for :secret_code, url: url_for(  :action => :generate_code ), :html => { :class => "form-horizontal"} do |f| %>
 
  <%= select_tag :times, options_for_select([['1', '1'],['10','10'],['20','20'],['50','50'],['100','100']],:selected => '10') , :class => 'input-large'%>
  <div>
    <br />
   <%= f.submit 'generate_code' , :class => 'btn btn-primary'%>
  </div>
  <% end %>

<br />
<%= link_to 'New Secret code', new_secret_code_path %>
<% end %>

app/views/secret_codes/new.html.erb
<h1>New secret_code</h1>

<%= render 'form' %>

<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @secret_code.user_id %>
</p>

<p>
  <b>Code:</b>
  <%= @secret_code.code %>
</p>


<%= link_to 'Edit', edit_secret_code_path(@secret_code) %> |
<%= link_to 'Back', secret_codes_path %>